from enum import Enum

NUM_PORTFOLIOS = 10000
TRADING_DAYS_PER_YEAR = 252

DEFAULT_START = "2020-01-01"
DEFAULT_END = "2026-04-02"
DEFAULT_INTERVAL = "1d"

RISK_FREE_RATE = 0.02
LEVERAGE_RATIO = 2.0
MAX_KELLY_LEVERAGE = 3.0
RISK_AVERSION = 3.0

DEFAULT_RISK_FREE_RATE = 0.0
DEFAULT_LEVERAGE_RATIO = 2.0
DEFAULT_RISK_AVERSION = 3.0
DEFAULT_KELLY_MAX_LEVERAGE = 3.0

class Ticker(Enum):
    BTC = "BTC-USD"
    ETH = "ETH-USD"
    SPXTR = "^SP500TR"
    AAPL = "AAPL"
    XAU = "GC=F"
    MSFT = "MSFT"
    AMZN = "AMZN"
    GOOGL = "GOOGL"
    JPM = "JPM"
    XOM = "XOM"
    JNJ = "JNJ"
    PG = "PG"
    KO = "KO"
    DIS = "DIS"
    NVDA = "NVDA"
    SPY = "SPY"
    QQQ = "QQQ"
    GLD = "GLD"
    TLT = "TLT"
    IWM = "IWM"


ACTIVE_ASSETS = [
    Ticker.BTC,
    Ticker.ETH,
    Ticker.SPXTR,
    Ticker.AAPL,
    Ticker.XAU,
    Ticker.NVDA,
]